name: caller_workflow
on: 
 workflow_dispatch:
  inputs:
   number1:
    description: 'Enter first number'     
    required: true
   number2:
    description: 'Enter second number'     
    required: true
env:
 number1: ${{ github.event.inputs.number1 }}
 number2: ${{ github.event.inputs.number2 }}

jobs:
 job1:
   runs-on: ubuntu-latest
   steps:
   - name: resusing addtitional workflow
   - uses: goyal20nikita/ReusableWorkflow/blob/main/.github/workflows/addition.yaml@main
     with:
      number1: $number1
      number2: $number2
   - name: resusing subtraction workflow
   - uses: goyal20nikita/ReusableWorkflow/blob/main/.github/workflows/subtraction.yaml@main
     with:
      number1: $number1
      number2: $number2
  
     
     
 
 
 
