name: caller_workflow
on: 
 workflow_dispatch:
  inputs:
   number1:
    description: 'Enter first number'     
    required: true
   number2:
    description: 'Enter second number'     
    required: true
env:
 number1: ${{ github.event.inputs.number1 }}
 number2: ${{ github.event.inputs.number2 }}

jobs:
 job1:
   runs-on: ubuntu-latest
   steps:
   - uses: goyal20nikita/ReusableWorkflow/.github/workflows/test.yaml@main
  
  
     
     
 
 
 
